export const MOCK_EVENTS = [
  {
    id: "1",
    title: "Chương Trình Frontend",
    description: "Bắt đầu chương trình thực tập Frontend Development",
    type: "program",
    date: new Date(2025, 10, 25),
    details: "Tìm hiểu về React, TypeScript, và các công nghệ Frontend hiện đại",
  },
  {
    id: "2",
    title: "Xây Dựng Component UI",
    description: "Thiết kế và phát triển hệ thống component",
    type: "task",
    date: new Date(2025, 11, 1),
    dueDate: new Date(2025, 11, 8),
    details: "Tạo 10 component UI cơ bản: Button, Card, Input, Modal, v.v.",
  },
  {
    id: "3",
    title: "Deadline: Hoàn Thành Task 1",
    description: "Hạn chót cho nhiệm vụ đầu tiên",
    type: "deadline",
    date: new Date(2025, 11, 8),
    details: "Phải hoàn thành và review tất cả components",
  },
  {
    id: "4",
    title: "Học Next.js Advanced",
    description: "Chuyên sâu về Server Components và API Routes",
    type: "task",
    date: new Date(2025, 11, 10),
    dueDate: new Date(2025, 11, 17),
    details: "Tìm hiểu App Router, Data Fetching, Middleware",
  },
  {
    id: "5",
    title: "Deadline: Dự Án Cuối Cùng",
    description: "Hạn nộp dự án final",
    type: "deadline",
    date: new Date(2025, 11, 24),
    details: "Dự án full-stack có database, authentication, và deployment",
  },
  {
    id: "6",
    title: "Code Review & Feedback",
    description: "Nhận xét từ mentor về code quality",
    type: "task",
    date: new Date(2025, 11, 18),
    details: "Meeting 1 giờ để discuss improvements",
  },
];
